# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_DB StudentTemplateDB
ENV POSTGRES_USER master
ENV POSTGRES_PASSWORD ekka

# Copy your SQL schema or initialization script into the container
COPY init.sql /docker-entrypoint-initdb.d/